// <auto-generated />
using System;
using Catalog.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Catalog.Api.Migrations
{
    [DbContext(typeof(CatalogContext))]
    [Migration("20210511160838_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.6");

            modelBuilder.Entity("Catalog.Api.Data.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedTimestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedTimestamp = new DateTime(2021, 5, 11, 17, 8, 37, 835, DateTimeKind.Local).AddTicks(5018),
                            Name = "Mobile Phones",
                            UpdatedTimestamp = new DateTime(2021, 5, 11, 17, 8, 37, 838, DateTimeKind.Local).AddTicks(5739)
                        },
                        new
                        {
                            Id = 2,
                            CreatedTimestamp = new DateTime(2021, 5, 11, 17, 8, 37, 838, DateTimeKind.Local).AddTicks(6541),
                            Name = "Audio Visual",
                            UpdatedTimestamp = new DateTime(2021, 5, 11, 17, 8, 37, 838, DateTimeKind.Local).AddTicks(6560)
                        },
                        new
                        {
                            Id = 3,
                            CreatedTimestamp = new DateTime(2021, 5, 11, 17, 8, 37, 838, DateTimeKind.Local).AddTicks(6565),
                            Name = "Clothing",
                            UpdatedTimestamp = new DateTime(2021, 5, 11, 17, 8, 37, 838, DateTimeKind.Local).AddTicks(6568)
                        });
                });

            modelBuilder.Entity("Catalog.Api.Data.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageFile")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
                            ImageFile = "product-1.png",
                            Name = "iPhone 12",
                            Price = 899.99m,
                            Summary = "Latest iPhone 12 with Night Mode"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Description = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
                            ImageFile = "product-2.png",
                            Name = "Panasonic 60 inch TV",
                            Price = 1999.99m,
                            Summary = "Big screen TV with Ultra HD"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Description = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
                            ImageFile = "product-3.png",
                            Name = "North Face Hoody",
                            Price = 49.99m,
                            Summary = "Extra warm fleece hoody"
                        });
                });

            modelBuilder.Entity("Catalog.Api.Data.Entities.Product", b =>
                {
                    b.HasOne("Catalog.Api.Data.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
